apiVersion: documentdb.azure.com/v20251015
kind: CassandraDataCenter
metadata:
  name: aso-cassandra-datacenter
  namespace: default
spec:
  azureName: aso-cassandra-datacenter
  owner:
    name: aso-cassandra-cluster
  properties:
    dataCenterLocation: eastus
    delegatedSubnetReference:
      group: network.azure.com
      kind: VirtualNetworksSubnet
      name: cassandra-subnet
    nodeCount: 3
    sku: Standard_DS14_v2
