apiVersion: containerservice.azure.com/v20260301
kind: ManagedClustersAgentPool
metadata:
  name: pool20260301
  namespace: default
spec:
  owner:
    name: sample-managedcluster-20260301
  count: 1
  vmSize: Standard_DS2_v2
  osType: Linux
  osSKU: AzureContainerLinux
  mode: User
