apiVersion: storage.azure.com/v1api20230101
kind: StorageAccountsBlobServicesContainer
metadata:
  name: aso-sample-deploymentpackage
  namespace: default
spec:
  azureName: deploymentpackage
  owner:
    name: aso-sample-flex-blobservice
