typeTransformers:
  - name: ContainerApp_Spec;ManagedEnvironment_Spec;Job_Spec;SessionPool_Spec
    property: Identity
    target:
      name: ManagedServiceIdentity
      version: v6
      optional: true
    because: Multiple incompatible versions of ManagedServiceIdentity are being imported from different versions of common

  - name: ContainerApp_STATUS;ManagedEnvironment_STATUS;Job_STATUS;SessionPool_STATUS
    property: Identity
    target:
      name: ManagedServiceIdentity_STATUS
      version: v6
      optional: true
    because: Multiple incompatible versions of ManagedServiceIdentity_STATUS are being imported from different versions of common

groupModelConfiguration:
  2025-01-01:
    ContainerApp:
      $exportAs: ContainerApp
      $supportedFrom: v2.15.0
      $generatedConfigs:
        EventStreamEndpoint: $.Status.EventStreamEndpoint
        Fqdn: $.Status.LatestRevisionFqdn
    ContainerApps_AuthConfig:
      $exportAs: AuthConfig
      $supportedFrom: v2.15.0
    RegistryCredentials:
      passwordSecretRef:
        $importSecretMode: never
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    ServiceBind:
      ServiceId:
        $referenceType: arm
    Secret:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    ContainerApp_Spec:
      ManagedBy:
        $referenceType: arm
    ContainerApp_Properties_Spec:
      EnvironmentId:
        $referenceType: arm
      ManagedEnvironmentId:
        $referenceType: arm
    CustomDomain:
      CertificateId:
        $referenceType: arm
    OpenIdConnectConfig:
      TokenEndpoint:
        $importSecretMode: never
    ManagedEnvironment:
      $exportAs: ManagedEnvironment
      $supportedFrom: v2.15.0
    VnetConfiguration:
      InfrastructureSubnetId:
        $referenceType: arm
    Job:
      $exportAs: Job
      $supportedFrom: v2.15.0
    Job_Properties_Spec:
      EnvironmentId:
        $referenceType: arm
    IdentitySettings:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    HttpScaleRule:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    TcpScaleRule:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    CustomScaleRule:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    JobScaleRule:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    QueueScaleRule:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    CertificateKeyVaultProperties:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
  2024-03-01:
    ContainerApp:
      $exportAs: ContainerApp
      $supportedFrom: v2.12.0
      $generatedConfigs:
        EventStreamEndpoint: $.Status.EventStreamEndpoint
        Fqdn: $.Status.LatestRevisionFqdn
    ContainerApps_AuthConfig:
      $exportAs: AuthConfig
      $supportedFrom: v2.12.0
    RegistryCredentials:
      passwordSecretRef:
        $importSecretMode: never
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    ServiceBind:
      ServiceId:
        $referenceType: arm
    Secret:
      Identity:
        $referenceType: arm+wellknown # permits `system` to use a system-assigned identity
    ContainerApp_Spec:
      ManagedBy:
        $referenceType: arm
    ContainerApp_Properties_Spec:
      EnvironmentId:
        $referenceType: arm
      ManagedEnvironmentId:
        $referenceType: arm
    CustomDomain:
      CertificateId:
        $referenceType: arm
    OpenIdConnectConfig:
      TokenEndpoint:
        $importSecretMode: never
    ManagedEnvironment:
      $exportAs: ManagedEnvironment
      $supportedFrom: v2.12.0
    VnetConfiguration:
      InfrastructureSubnetId:
        $referenceType: arm
    Job:
      $exportAs: Job
      $supportedFrom: v2.12.0
    Job_Properties_Spec:
      EnvironmentId:
        $referenceType: arm
