typeTransformers:
  - name: ConfigurationStore_Spec
    property: SystemData
    remove: true
    because: This property should be marked readonly in Swagger
groupModelConfiguration:
  2022-05-01:
    ConfigurationStore:
      $exportAs: ConfigurationStore
      $supportedFrom: v2.0.0-beta.3
      $azureGeneratedSecrets:
        - PrimaryKeyID
        - PrimaryKey
        - PrimaryConnectionString
        - SecondaryKeyID
        - SecondaryKey
        - SecondaryConnectionString
        - PrimaryReadOnlyKeyID
        - PrimaryReadOnlyKey
        - PrimaryReadOnlyConnectionString
        - SecondaryReadOnlyKeyID
        - SecondaryReadOnlyKey
        - SecondaryReadOnlyConnectionString
    PrivateEndpointConnectionReference_STATUS:
      # This is a subresource but it's not labelled as one in their Swagger, instead there's a duplicate entity
      # shaped the same called PrivateEndpointConnection which is labelled as a resource. We want to prune this.
      $isResource: true
  2024-06-01:
    ConfigurationStore:
      $exportAs: ConfigurationStore
      $supportedFrom: v2.18.0
      $azureGeneratedSecrets:
        - PrimaryKeyID
        - PrimaryKey
        - PrimaryConnectionString
        - SecondaryKeyID
        - SecondaryKey
        - SecondaryConnectionString
        - PrimaryReadOnlyKeyID
        - PrimaryReadOnlyKey
        - PrimaryReadOnlyConnectionString
        - SecondaryReadOnlyKeyID
        - SecondaryReadOnlyKey
        - SecondaryReadOnlyConnectionString
    ConfigurationStores_KeyValue:
      $exportAs: KeyValue
      $supportedFrom: v2.18.0
    ConfigurationStores_Replica:
      $exportAs: Replica
      $supportedFrom: v2.18.0
    ConfigurationStores_Snapshot:
      $exportAs: Snapshot
      $supportedFrom: v2.18.0
