apiVersion: containerservice.azure.com/v20260501
kind: IdentityBinding
metadata:
  name: sampleidentitybinding
  namespace: default
spec:
  owner:
    name: sample-managedcluster-20260501
  properties:
    managedIdentity:
      resourceReference:
        group: managedidentity.azure.com
        kind: UserAssignedIdentity
        name: sample-identitybinding-identity
