apiVersion: compute.azure.com/v20220301
kind: VirtualMachinesExtension
metadata:
  name: myvmextension20220301
  namespace: default
spec:
  owner:
    name: aso-sample-vm
  publisher: Microsoft.ManagedServices
  type: ApplicationHealthLinux
  typeHandlerVersion: "1.0"
  location: westus3
