// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_AuthorizationRule_STATUSARM_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of AuthorizationRule_STATUSARM via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForAuthorizationRule_STATUSARM, AuthorizationRule_STATUSARMGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForAuthorizationRule_STATUSARM runs a test to see if a specific instance of AuthorizationRule_STATUSARM round trips to JSON and back losslessly
func RunJSONSerializationTestForAuthorizationRule_STATUSARM(subject AuthorizationRule_STATUSARM) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual AuthorizationRule_STATUSARM
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of AuthorizationRule_STATUSARM instances for property testing - lazily instantiated by
// AuthorizationRule_STATUSARMGenerator()
var authorizationRule_STATUSARMGenerator gopter.Gen

// AuthorizationRule_STATUSARMGenerator returns a generator of AuthorizationRule_STATUSARM instances for property testing.
// We first initialize authorizationRule_STATUSARMGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func AuthorizationRule_STATUSARMGenerator() gopter.Gen {
	if authorizationRule_STATUSARMGenerator != nil {
		return authorizationRule_STATUSARMGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForAuthorizationRule_STATUSARM(generators)
	authorizationRule_STATUSARMGenerator = gen.Struct(reflect.TypeOf(AuthorizationRule_STATUSARM{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForAuthorizationRule_STATUSARM(generators)
	AddRelatedPropertyGeneratorsForAuthorizationRule_STATUSARM(generators)
	authorizationRule_STATUSARMGenerator = gen.Struct(reflect.TypeOf(AuthorizationRule_STATUSARM{}), generators)

	return authorizationRule_STATUSARMGenerator
}

// AddIndependentPropertyGeneratorsForAuthorizationRule_STATUSARM is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForAuthorizationRule_STATUSARM(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Location"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForAuthorizationRule_STATUSARM is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForAuthorizationRule_STATUSARM(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(AuthorizationRule_Properties_STATUSARMGenerator())
	gens["SystemData"] = gen.PtrOf(SystemData_STATUSARMGenerator())
}

func Test_AuthorizationRule_Properties_STATUSARM_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of AuthorizationRule_Properties_STATUSARM via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForAuthorizationRule_Properties_STATUSARM, AuthorizationRule_Properties_STATUSARMGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForAuthorizationRule_Properties_STATUSARM runs a test to see if a specific instance of AuthorizationRule_Properties_STATUSARM round trips to JSON and back losslessly
func RunJSONSerializationTestForAuthorizationRule_Properties_STATUSARM(subject AuthorizationRule_Properties_STATUSARM) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual AuthorizationRule_Properties_STATUSARM
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of AuthorizationRule_Properties_STATUSARM instances for property testing - lazily instantiated by
// AuthorizationRule_Properties_STATUSARMGenerator()
var authorizationRule_Properties_STATUSARMGenerator gopter.Gen

// AuthorizationRule_Properties_STATUSARMGenerator returns a generator of AuthorizationRule_Properties_STATUSARM instances for property testing.
func AuthorizationRule_Properties_STATUSARMGenerator() gopter.Gen {
	if authorizationRule_Properties_STATUSARMGenerator != nil {
		return authorizationRule_Properties_STATUSARMGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForAuthorizationRule_Properties_STATUSARM(generators)
	authorizationRule_Properties_STATUSARMGenerator = gen.Struct(reflect.TypeOf(AuthorizationRule_Properties_STATUSARM{}), generators)

	return authorizationRule_Properties_STATUSARMGenerator
}

// AddIndependentPropertyGeneratorsForAuthorizationRule_Properties_STATUSARM is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForAuthorizationRule_Properties_STATUSARM(gens map[string]gopter.Gen) {
	gens["Rights"] = gen.SliceOf(gen.OneConstOf(AuthorizationRule_Properties_Rights_STATUSListen, AuthorizationRule_Properties_Rights_STATUSManage, AuthorizationRule_Properties_Rights_STATUSSend))
}

func Test_SystemData_STATUSARM_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of SystemData_STATUSARM via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForSystemData_STATUSARM, SystemData_STATUSARMGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForSystemData_STATUSARM runs a test to see if a specific instance of SystemData_STATUSARM round trips to JSON and back losslessly
func RunJSONSerializationTestForSystemData_STATUSARM(subject SystemData_STATUSARM) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual SystemData_STATUSARM
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of SystemData_STATUSARM instances for property testing - lazily instantiated by
// SystemData_STATUSARMGenerator()
var systemData_STATUSARMGenerator gopter.Gen

// SystemData_STATUSARMGenerator returns a generator of SystemData_STATUSARM instances for property testing.
func SystemData_STATUSARMGenerator() gopter.Gen {
	if systemData_STATUSARMGenerator != nil {
		return systemData_STATUSARMGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForSystemData_STATUSARM(generators)
	systemData_STATUSARMGenerator = gen.Struct(reflect.TypeOf(SystemData_STATUSARM{}), generators)

	return systemData_STATUSARMGenerator
}

// AddIndependentPropertyGeneratorsForSystemData_STATUSARM is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForSystemData_STATUSARM(gens map[string]gopter.Gen) {
	gens["CreatedAt"] = gen.PtrOf(gen.AlphaString())
	gens["CreatedBy"] = gen.PtrOf(gen.AlphaString())
	gens["CreatedByType"] = gen.PtrOf(gen.OneConstOf(
		SystemData_CreatedByType_STATUSApplication,
		SystemData_CreatedByType_STATUSKey,
		SystemData_CreatedByType_STATUSManagedIdentity,
		SystemData_CreatedByType_STATUSUser))
	gens["LastModifiedAt"] = gen.PtrOf(gen.AlphaString())
	gens["LastModifiedBy"] = gen.PtrOf(gen.AlphaString())
	gens["LastModifiedByType"] = gen.PtrOf(gen.OneConstOf(
		SystemData_LastModifiedByType_STATUSApplication,
		SystemData_LastModifiedByType_STATUSKey,
		SystemData_LastModifiedByType_STATUSManagedIdentity,
		SystemData_LastModifiedByType_STATUSUser))
}
