// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"pgregory.net/rapid"
	"testing"
)

func Test_FederatedIdentityCredentialProperties_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		return
	}

	rapid.Check(t, RunJSONSerializationTestForFederatedIdentityCredentialProperties_STATUS)
}

// RunJSONSerializationTestForFederatedIdentityCredentialProperties_STATUS runs a test to see if a specific instance of FederatedIdentityCredentialProperties_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForFederatedIdentityCredentialProperties_STATUS(t *rapid.T) {
	subject := FederatedIdentityCredentialProperties_STATUSGenerator().Draw(t, "subject")
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		t.Fatal(err)
	}

	// Deserialize back into memory
	var actual FederatedIdentityCredentialProperties_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		t.Fatal(err)
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		t.Error(result)
	}
}

// Generator of FederatedIdentityCredentialProperties_STATUS instances for property testing - lazily instantiated by
// FederatedIdentityCredentialProperties_STATUSGenerator()
var federatedIdentityCredentialProperties_STATUSGenerator *rapid.Generator[FederatedIdentityCredentialProperties_STATUS]

// FederatedIdentityCredentialProperties_STATUSGenerator returns a generator of FederatedIdentityCredentialProperties_STATUS instances for property testing.
func FederatedIdentityCredentialProperties_STATUSGenerator() *rapid.Generator[FederatedIdentityCredentialProperties_STATUS] {
	if federatedIdentityCredentialProperties_STATUSGenerator != nil {
		return federatedIdentityCredentialProperties_STATUSGenerator
	}

	ptrString := rapid.Ptr(rapid.String(), true)
	audiences := rapid.SliceOf(rapid.String())

	federatedIdentityCredentialProperties_STATUSGenerator = rapid.Custom(func(t *rapid.T) FederatedIdentityCredentialProperties_STATUS {
		var result FederatedIdentityCredentialProperties_STATUS
		result.Audiences = audiences.Draw(t, "Audiences")
		result.Issuer = ptrString.Draw(t, "Issuer")
		result.Subject = ptrString.Draw(t, "Subject")
		return result
	})

	return federatedIdentityCredentialProperties_STATUSGenerator
}

func Test_FederatedIdentityCredential_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		return
	}

	rapid.Check(t, RunJSONSerializationTestForFederatedIdentityCredential_STATUS)
}

// RunJSONSerializationTestForFederatedIdentityCredential_STATUS runs a test to see if a specific instance of FederatedIdentityCredential_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForFederatedIdentityCredential_STATUS(t *rapid.T) {
	subject := FederatedIdentityCredential_STATUSGenerator().Draw(t, "subject")
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		t.Fatal(err)
	}

	// Deserialize back into memory
	var actual FederatedIdentityCredential_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		t.Fatal(err)
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		t.Error(result)
	}
}

// Generator of FederatedIdentityCredential_STATUS instances for property testing - lazily instantiated by
// FederatedIdentityCredential_STATUSGenerator()
var federatedIdentityCredential_STATUSGenerator *rapid.Generator[FederatedIdentityCredential_STATUS]

// FederatedIdentityCredential_STATUSGenerator returns a generator of FederatedIdentityCredential_STATUS instances for property testing.
func FederatedIdentityCredential_STATUSGenerator() *rapid.Generator[FederatedIdentityCredential_STATUS] {
	if federatedIdentityCredential_STATUSGenerator != nil {
		return federatedIdentityCredential_STATUSGenerator
	}

	ptrString := rapid.Ptr(rapid.String(), true)
	properties := rapid.Ptr(FederatedIdentityCredentialProperties_STATUSGenerator(), true)

	federatedIdentityCredential_STATUSGenerator = rapid.Custom(func(t *rapid.T) FederatedIdentityCredential_STATUS {
		var result FederatedIdentityCredential_STATUS
		result.Id = ptrString.Draw(t, "Id")
		result.Name = ptrString.Draw(t, "Name")
		result.Properties = properties.Draw(t, "Properties")
		result.Type = ptrString.Draw(t, "Type")
		return result
	})

	return federatedIdentityCredential_STATUSGenerator
}
