apiVersion: web.azure.com/v20250501
kind: Site
metadata:
  name: aso-sample-function-site
  namespace: default
spec:
  enabled: true
  location: northeurope
  owner:
    name: aso-sample-rg
  kind: functionapp,linux
  httpsOnly: true
  serverFarmReference:
    group: web.azure.com
    kind: ServerFarm
    name: aso-sample-appservice
  identity:
    type: UserAssigned
    userAssignedIdentities:
      - reference:
          group: managedidentity.azure.com
          kind: UserAssignedIdentity
          name: aso-sample-flex-identity
  functionAppConfig:
    deployment:
      storage:
        type: blobContainer
        value: https://asosampleflexstorage.blob.core.windows.net/deploymentpackage
        authentication:
          type: UserAssignedIdentity
          userAssignedIdentityResourceReference:
            group: managedidentity.azure.com
            kind: UserAssignedIdentity
            name: aso-sample-flex-identity
    runtime:
      name: dotnet-isolated
      version: "8.0"
    scaleAndConcurrency:
      instanceMemoryMB: 2048
      maximumInstanceCount: 100
