apiVersion: apimanagement.azure.com/v20220801
kind: Backend
metadata:
  name: sampleapimbackend
  namespace: default
spec:
  description: Sample backend
  protocol: http
  url: http://www.contoso.com
  owner:
    name: sampleapimservice
