apiVersion: apimanagement.azure.com/v20220801
kind: Subscription
metadata:
  name: sampleapimsubscription
  namespace: default
spec:
  displayName: Sample subscription
  scope: /apis
  owner:
    name: sampleapimservice
