apiVersion: eventgrid.azure.com/v20250215
kind: Domain
metadata:
  name: sample-domain
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  publicNetworkAccess: Enabled
  disableLocalAuth: false
