apiVersion: eventhub.azure.com/v1api20240101
kind: NamespacesEventhub
metadata:
  name: sample-eventhub
  namespace: default
spec:
  owner:
    name: aso-sample-eventhub-namespace
  messageRetentionInDays: 1
  partitionCount: 2
