apiVersion: dbformysql.azure.com/v20250601preview
kind: FlexibleServersConfiguration
metadata:
  name: sampleconfiguration
  namespace: default
spec:
  owner:
    name: samplemysql
  source: user-override
  value: "300"
