---
version: 2
interactions:
    - id: 0
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        transfer_encoding: []
        trailer: {}
        host: graph.microsoft.com
        remote_addr: ""
        request_uri: ""
        body: ""
        form: {}
        headers:
            Accept:
                - application/json
            Test-Request-Attempt:
                - "0"
        url: https://graph.microsoft.com/v1.0/applications?%24filter=displayName%20eq%20%27ASO%20Test%20Application%27
        method: GET
      response:
        proto: HTTP/2.0
        proto_major: 2
        proto_minor: 0
        transfer_encoding: []
        trailer: {}
        content_length: -1
        uncompressed: true
        body: '{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#applications","value":[]}'
        headers:
            Cache-Control:
                - no-cache
            Content-Type:
                - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
            Odata-Version:
                - "4.0"
            Strict-Transport-Security:
                - max-age=31536000
            Vary:
                - Accept-Encoding
        status: 200 OK
        code: 200
        duration: 1.342279062s
    - id: 1
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        transfer_encoding: []
        trailer: {}
        host: graph.microsoft.com
        remote_addr: ""
        request_uri: ""
        body: '{"@odata.type":"#microsoft.graph.application","displayName":"ASO Test Application","signInAudience":"AzureADMyOrg"}'
        form: {}
        headers:
            Accept:
                - application/json
            Content-Type:
                - application/json
            Test-Request-Hash:
                - 527f6e1d3ca5b71ed68212b61a2cceaba8db1728ee8006c05c2631f82081cba5
        url: https://graph.microsoft.com/v1.0/applications
        method: POST
      response:
        proto: HTTP/2.0
        proto_major: 2
        proto_minor: 0
        transfer_encoding: []
        trailer: {}
        content_length: -1
        uncompressed: true
        body: '{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#applications/$entity","id":"48963276-5651-4fe7-95da-84ac129c5f71","deletedDateTime":null,"appId":"035d1116-3bc2-424e-96e6-065dc5945ebc","applicationTemplateId":null,"disabledByMicrosoftStatus":null,"createdByAppId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","createdDateTime":"2001-02-03T04:05:06Z","displayName":"ASO Test Application","description":null,"groupMembershipClaims":null,"identifierUris":[],"isDeviceOnlyAuthSupported":null,"isFallbackPublicClient":null,"nativeAuthenticationApisEnabled":null,"notes":null,"publisherDomain":"bevanarpsoutlook.onmicrosoft.com","serviceManagementReference":null,"signInAudience":"AzureADMyOrg","tags":[],"tokenEncryptionKeyId":null,"uniqueName":null,"samlMetadataUrl":null,"defaultRedirectUri":null,"certification":null,"optionalClaims":null,"servicePrincipalLockConfiguration":null,"requestSignatureVerification":null,"addIns":[],"api":{"acceptMappedClaims":null,"knownClientApplications":[],"requestedAccessTokenVersion":null,"oauth2PermissionScopes":[],"preAuthorizedApplications":[]},"appRoles":[],"info":{"logoUrl":null,"marketingUrl":null,"privacyStatementUrl":null,"supportUrl":null,"termsOfServiceUrl":null},"keyCredentials":[],"parentalControlSettings":{"countriesBlockedForMinors":[],"legalAgeGroupRule":"Allow"},"passwordCredentials":[],"publicClient":{"redirectUris":[]},"requiredResourceAccess":[],"verifiedPublisher":{"displayName":null,"verifiedPublisherId":null,"addedDateTime":null},"web":{"homePageUrl":null,"logoutUrl":null,"redirectUris":[],"implicitGrantSettings":{"enableAccessTokenIssuance":false,"enableIdTokenIssuance":false},"redirectUriSettings":[]},"spa":{"redirectUris":[]}}'
        headers:
            Cache-Control:
                - no-cache
            Content-Type:
                - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
            Location:
                - https://graph.microsoft.com/v1.0/00000000-0000-0000-0000-000000000000/directoryObjects/48963276-5651-4fe7-95da-84ac129c5f71/Microsoft.DirectoryServices.Application
            Odata-Version:
                - "4.0"
            Strict-Transport-Security:
                - max-age=31536000
            Vary:
                - Accept-Encoding
        status: 201 Created
        code: 201
        duration: 374.549799ms
    - id: 2
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        transfer_encoding: []
        trailer: {}
        host: graph.microsoft.com
        remote_addr: ""
        request_uri: ""
        body: ""
        form: {}
        headers:
            Accept:
                - application/json
            Test-Request-Attempt:
                - "0"
        url: https://graph.microsoft.com/v1.0/applications/48963276-5651-4fe7-95da-84ac129c5f71
        method: GET
      response:
        proto: HTTP/2.0
        proto_major: 2
        proto_minor: 0
        transfer_encoding: []
        trailer: {}
        content_length: -1
        uncompressed: true
        body: '{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#applications/$entity","id":"48963276-5651-4fe7-95da-84ac129c5f71","deletedDateTime":null,"appId":"035d1116-3bc2-424e-96e6-065dc5945ebc","applicationTemplateId":null,"disabledByMicrosoftStatus":null,"createdByAppId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","createdDateTime":"2001-02-03T04:05:06Z","displayName":"ASO Test Application","description":null,"groupMembershipClaims":null,"identifierUris":[],"isDeviceOnlyAuthSupported":null,"isFallbackPublicClient":null,"nativeAuthenticationApisEnabled":null,"notes":null,"publisherDomain":"bevanarpsoutlook.onmicrosoft.com","serviceManagementReference":null,"signInAudience":"AzureADMyOrg","tags":[],"tokenEncryptionKeyId":null,"uniqueName":null,"samlMetadataUrl":null,"defaultRedirectUri":null,"certification":null,"optionalClaims":null,"servicePrincipalLockConfiguration":null,"requestSignatureVerification":null,"addIns":[],"api":{"acceptMappedClaims":null,"knownClientApplications":[],"requestedAccessTokenVersion":null,"oauth2PermissionScopes":[],"preAuthorizedApplications":[]},"appRoles":[],"info":{"logoUrl":null,"marketingUrl":null,"privacyStatementUrl":null,"supportUrl":null,"termsOfServiceUrl":null},"keyCredentials":[],"parentalControlSettings":{"countriesBlockedForMinors":[],"legalAgeGroupRule":"Allow"},"passwordCredentials":[],"publicClient":{"redirectUris":[]},"requiredResourceAccess":[],"verifiedPublisher":{"displayName":null,"verifiedPublisherId":null,"addedDateTime":null},"web":{"homePageUrl":null,"logoutUrl":null,"redirectUris":[],"implicitGrantSettings":{"enableAccessTokenIssuance":false,"enableIdTokenIssuance":false},"redirectUriSettings":[]},"spa":{"redirectUris":[]}}'
        headers:
            Cache-Control:
                - no-cache
            Content-Type:
                - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
            Odata-Version:
                - "4.0"
            Strict-Transport-Security:
                - max-age=31536000
            Vary:
                - Accept-Encoding
        status: 200 OK
        code: 200
        duration: 241.381847ms
    - id: 3
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        transfer_encoding: []
        trailer: {}
        host: graph.microsoft.com
        remote_addr: ""
        request_uri: ""
        body: '{"@odata.type":"#microsoft.graph.application","@odata.context":"https://graph.microsoft.com/v1.0/$metadata#applications/$entity","createdByAppId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46"}'
        form: {}
        headers:
            Accept:
                - application/json
            Content-Type:
                - application/json
            Test-Request-Attempt:
                - "0"
        url: https://graph.microsoft.com/v1.0/applications/48963276-5651-4fe7-95da-84ac129c5f71
        method: PATCH
      response:
        proto: HTTP/2.0
        proto_major: 2
        proto_minor: 0
        transfer_encoding: []
        trailer: {}
        content_length: -1
        uncompressed: false
        body: ""
        headers:
            Cache-Control:
                - no-cache
            Strict-Transport-Security:
                - max-age=31536000
        status: 204 No Content
        code: 204
        duration: 241.274611ms
    - id: 4
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        transfer_encoding: []
        trailer: {}
        host: graph.microsoft.com
        remote_addr: ""
        request_uri: ""
        body: ""
        form: {}
        headers:
            Accept:
                - application/json
            Test-Request-Attempt:
                - "0"
        url: https://graph.microsoft.com/v1.0/applications/48963276-5651-4fe7-95da-84ac129c5f71
        method: DELETE
      response:
        proto: HTTP/2.0
        proto_major: 2
        proto_minor: 0
        transfer_encoding: []
        trailer: {}
        content_length: -1
        uncompressed: false
        body: ""
        headers:
            Cache-Control:
                - no-cache
            Strict-Transport-Security:
                - max-age=31536000
        status: 204 No Content
        code: 204
        duration: 424.490807ms
