---
version: 2
interactions:
    - id: 0
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        host: graph.microsoft.com
        form:
            $filter:
                - displayName eq 'ASO Test Application'
        headers:
            Accept:
                - application/json
        url: https://graph.microsoft.com/v1.0/applications?%24filter=displayName%20eq%20%27ASO%20Test%20Application%27
        method: GET
      response:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        transfer_encoding:
            - chunked
        content_length: -1
        uncompressed: true
        body: '{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#applications","value":[]}'
        headers:
            Cache-Control:
                - no-cache
            Content-Type:
                - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
            Odata-Version:
                - "4.0"
            Strict-Transport-Security:
                - max-age=31536000
            Vary:
                - Accept-Encoding
        status: 200 OK
        code: 200
        duration: 309.846601ms
    - id: 1
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        host: graph.microsoft.com
        body: '{"spa":null,"groupMembershipClaims":null,"description":null,"web":null,"publicClient":null,"isFallbackPublicClient":null,"@odata.type":"#microsoft.graph.application","displayName":"ASO Test Application","signInAudience":"AzureADMyOrg"}'
        headers:
            Accept:
                - application/json
            Content-Type:
                - application/json
            Test-Request-Canonical-Hash:
                - 8b9b6fa3b2aab5dd17d6778f477dd4bb02b20b4c9e9b6c0130772b8261631c7b
            Test-Request-Hash:
                - 180ead3657b849898e8e9c1a6a93ffe37754c55bc5ed6045171dfcbbabbeb41c
        url: https://graph.microsoft.com/v1.0/applications
        method: POST
      response:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        transfer_encoding:
            - chunked
        content_length: -1
        uncompressed: true
        body: '{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#applications/$entity","id":"1ab82f11-ed83-4fd0-9968-5cfea5bc46ff","deletedDateTime":null,"appId":"9a82a37f-aaea-4561-b4a2-3f2d5166267c","applicationTemplateId":null,"disabledByMicrosoftStatus":null,"createdByAppId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","createdDateTime":"2001-02-03T04:05:06Z","displayName":"ASO Test Application","description":null,"groupMembershipClaims":null,"identifierUris":[],"isDeviceOnlyAuthSupported":null,"isDisabled":null,"isFallbackPublicClient":null,"nativeAuthenticationApisEnabled":null,"notes":null,"publisherDomain":"redactedtenant.onmicrosoft.com","serviceManagementReference":null,"signInAudience":"AzureADMyOrg","tags":[],"tokenEncryptionKeyId":null,"uniqueName":null,"samlMetadataUrl":null,"defaultRedirectUri":null,"certification":null,"optionalClaims":null,"requestSignatureVerification":null,"addIns":[],"api":{"acceptMappedClaims":null,"knownClientApplications":[],"requestedAccessTokenVersion":null,"oauth2PermissionScopes":[],"preAuthorizedApplications":[]},"appRoles":[],"info":{"logoUrl":null,"marketingUrl":null,"privacyStatementUrl":null,"supportUrl":null,"termsOfServiceUrl":null},"keyCredentials":[],"parentalControlSettings":{"countriesBlockedForMinors":[],"legalAgeGroupRule":"Allow"},"passwordCredentials":[],"publicClient":{"redirectUris":[]},"requiredResourceAccess":[],"verifiedPublisher":{"displayName":null,"verifiedPublisherId":null,"addedDateTime":null},"web":{"homePageUrl":null,"logoutUrl":null,"redirectUris":[],"implicitGrantSettings":{"enableAccessTokenIssuance":false,"enableIdTokenIssuance":false},"redirectUriSettings":[]},"servicePrincipalLockConfiguration":{"isEnabled":true,"allProperties":true,"credentialsWithUsageVerify":null,"credentialsWithUsageSign":null,"identifierUris":null,"tokenEncryptionKeyId":null},"spa":{"redirectUris":[]}}'
        headers:
            Cache-Control:
                - no-cache
            Content-Type:
                - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
            Location:
                - https://graph.microsoft.com/v1.0/00000000-0000-0000-0000-000000000000/directoryObjects/1ab82f11-ed83-4fd0-9968-5cfea5bc46ff/Microsoft.DirectoryServices.Application
            Odata-Version:
                - "4.0"
            Strict-Transport-Security:
                - max-age=31536000
            Vary:
                - Accept-Encoding
        status: 201 Created
        code: 201
        duration: 292.355445ms
    - id: 2
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        host: graph.microsoft.com
        headers:
            Accept:
                - application/json
        url: https://graph.microsoft.com/v1.0/applications/1ab82f11-ed83-4fd0-9968-5cfea5bc46ff
        method: GET
      response:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        transfer_encoding:
            - chunked
        content_length: -1
        uncompressed: true
        body: '{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#applications/$entity","id":"1ab82f11-ed83-4fd0-9968-5cfea5bc46ff","deletedDateTime":null,"appId":"9a82a37f-aaea-4561-b4a2-3f2d5166267c","applicationTemplateId":null,"disabledByMicrosoftStatus":null,"createdByAppId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","createdDateTime":"2001-02-03T04:05:06Z","displayName":"ASO Test Application","description":null,"groupMembershipClaims":null,"identifierUris":[],"isDeviceOnlyAuthSupported":null,"isDisabled":null,"isFallbackPublicClient":null,"nativeAuthenticationApisEnabled":null,"notes":null,"publisherDomain":"redactedtenant.onmicrosoft.com","serviceManagementReference":null,"signInAudience":"AzureADMyOrg","tags":[],"tokenEncryptionKeyId":null,"uniqueName":null,"samlMetadataUrl":null,"defaultRedirectUri":null,"certification":null,"optionalClaims":null,"requestSignatureVerification":null,"addIns":[],"api":{"acceptMappedClaims":null,"knownClientApplications":[],"requestedAccessTokenVersion":null,"oauth2PermissionScopes":[],"preAuthorizedApplications":[]},"appRoles":[],"info":{"logoUrl":null,"marketingUrl":null,"privacyStatementUrl":null,"supportUrl":null,"termsOfServiceUrl":null},"keyCredentials":[],"parentalControlSettings":{"countriesBlockedForMinors":[],"legalAgeGroupRule":"Allow"},"passwordCredentials":[],"publicClient":{"redirectUris":[]},"requiredResourceAccess":[],"verifiedPublisher":{"displayName":null,"verifiedPublisherId":null,"addedDateTime":null},"web":{"homePageUrl":null,"logoutUrl":null,"redirectUris":[],"implicitGrantSettings":{"enableAccessTokenIssuance":false,"enableIdTokenIssuance":false},"redirectUriSettings":[]},"servicePrincipalLockConfiguration":{"isEnabled":true,"allProperties":true,"credentialsWithUsageVerify":null,"credentialsWithUsageSign":null,"identifierUris":null,"tokenEncryptionKeyId":null},"spa":{"redirectUris":[]}}'
        headers:
            Cache-Control:
                - no-cache
            Content-Type:
                - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
            Odata-Version:
                - "4.0"
            Strict-Transport-Security:
                - max-age=31536000
            Vary:
                - Accept-Encoding
        status: 200 OK
        code: 200
        duration: 74.263266ms
    - id: 3
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        host: graph.microsoft.com
        body: '{"spa":null,"publicClient":null,"groupMembershipClaims":null,"web":null,"isFallbackPublicClient":null,"description":null,"@odata.type":"#microsoft.graph.application","displayName":"ASO Test Application Updated","signInAudience":"AzureADMyOrg"}'
        headers:
            Accept:
                - application/json
            Content-Type:
                - application/json
            Test-Request-Canonical-Hash:
                - 05a65a6eca532ecda922cd32a664356b95a1e7e3e619ea02942b82e46ba80466
            Test-Request-Hash:
                - 6c8816b0127d598ac4bcfcc8644b1e38c33f6e32f6d93a99b508e48617b7c195
        url: https://graph.microsoft.com/v1.0/applications/1ab82f11-ed83-4fd0-9968-5cfea5bc46ff
        method: PATCH
      response:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        body: ""
        headers:
            Cache-Control:
                - no-cache
            Strict-Transport-Security:
                - max-age=31536000
        status: 204 No Content
        code: 204
        duration: 146.508844ms
    - id: 4
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        host: graph.microsoft.com
        headers:
            Accept:
                - application/json
        url: https://graph.microsoft.com/v1.0/applications/1ab82f11-ed83-4fd0-9968-5cfea5bc46ff
        method: GET
      response:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        transfer_encoding:
            - chunked
        content_length: -1
        uncompressed: true
        body: '{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#applications/$entity","id":"1ab82f11-ed83-4fd0-9968-5cfea5bc46ff","deletedDateTime":null,"appId":"9a82a37f-aaea-4561-b4a2-3f2d5166267c","applicationTemplateId":null,"disabledByMicrosoftStatus":null,"createdByAppId":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","createdDateTime":"2001-02-03T04:05:06Z","displayName":"ASO Test Application Updated","description":null,"groupMembershipClaims":null,"identifierUris":[],"isDeviceOnlyAuthSupported":null,"isDisabled":null,"isFallbackPublicClient":null,"nativeAuthenticationApisEnabled":null,"notes":null,"publisherDomain":"redactedtenant.onmicrosoft.com","serviceManagementReference":null,"signInAudience":"AzureADMyOrg","tags":[],"tokenEncryptionKeyId":null,"uniqueName":null,"samlMetadataUrl":null,"defaultRedirectUri":null,"certification":null,"optionalClaims":null,"requestSignatureVerification":null,"addIns":[],"api":{"acceptMappedClaims":null,"knownClientApplications":[],"requestedAccessTokenVersion":null,"oauth2PermissionScopes":[],"preAuthorizedApplications":[]},"appRoles":[],"info":{"logoUrl":null,"marketingUrl":null,"privacyStatementUrl":null,"supportUrl":null,"termsOfServiceUrl":null},"keyCredentials":[],"parentalControlSettings":{"countriesBlockedForMinors":[],"legalAgeGroupRule":"Allow"},"passwordCredentials":[],"publicClient":{"redirectUris":[]},"requiredResourceAccess":[],"verifiedPublisher":{"displayName":null,"verifiedPublisherId":null,"addedDateTime":null},"web":{"homePageUrl":null,"logoutUrl":null,"redirectUris":[],"implicitGrantSettings":{"enableAccessTokenIssuance":false,"enableIdTokenIssuance":false},"redirectUriSettings":[]},"servicePrincipalLockConfiguration":{"isEnabled":true,"allProperties":true,"credentialsWithUsageVerify":null,"credentialsWithUsageSign":null,"identifierUris":null,"tokenEncryptionKeyId":null},"spa":{"redirectUris":[]}}'
        headers:
            Cache-Control:
                - no-cache
            Content-Type:
                - application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
            Odata-Version:
                - "4.0"
            Strict-Transport-Security:
                - max-age=31536000
            Vary:
                - Accept-Encoding
        status: 200 OK
        code: 200
        duration: 72.44841ms
    - id: 5
      request:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        host: graph.microsoft.com
        headers:
            Accept:
                - application/json
        url: https://graph.microsoft.com/v1.0/applications/1ab82f11-ed83-4fd0-9968-5cfea5bc46ff
        method: DELETE
      response:
        proto: HTTP/1.1
        proto_major: 1
        proto_minor: 1
        content_length: 0
        body: ""
        headers:
            Cache-Control:
                - no-cache
            Strict-Transport-Security:
                - max-age=31536000
        status: 204 No Content
        code: 204
        duration: 113.268044ms
