# https://taskfile.dev

version: '3.7'

run: when_changed
output: prefixed

includes:
  mangle-test: ../mangle-test-json/Taskfile.yml

vars:
  GENERATOR_APP: aso-gen
  GENERATOR_ROOT: '{{.TASKFILE_DIR}}'
  TEST_OUT: '{{joinPath .TASKFILE_DIR ".." ".." ".." "reports"}}'

tasks:
  quick-checks:
    cmds:
      # Need to enforce these running in sequence as they can modify the same files
      - task: format-code
      - task: lint
      - task: unit-tests

  build:
    desc: Generate the {{.GENERATOR_APP}} binary.
    dir: '{{.GENERATOR_ROOT}}'
    cmds:
      - go build {{.LDFLAGS}} -o ../../bin/{{.GENERATOR_APP}} .

  unit-tests:
    desc: Run {{.GENERATOR_APP}} unit tests.
    dir: '{{.GENERATOR_ROOT}}'
    cmds:
      - go test ./... -tags=noexit -run '{{default ".*" .TEST_FILTER}}'

  unit-tests-cover:
    desc: Run {{.GENERATOR_APP}} unit tests and output coverage.
    dir: '{{.GENERATOR_ROOT}}'
    deps:
      - ensure-reports-dir
    cmds:
      - defer: # want to run even on failure
          task: mangle-test:produce-markdown-summary
          vars:
            INPUT_FILE: '{{.TEST_OUT}}/generator-unit-tests.json'
            OUTPUT_FILE: '{{.TEST_OUT}}/generator-unit-tests.md'
      - go test ./... -tags=noexit -race -covermode atomic -coverprofile='{{.TEST_OUT}}/generator-coverage.out' -json -coverpkg=./... -run '{{default ".*" .TEST_FILTER}}' > '{{.TEST_OUT}}/generator-unit-tests.json'

  lint:
    desc: Run {{.GENERATOR_APP}} fast lint checks.
    dir: '{{.GENERATOR_ROOT}}'
    cmds:
      - golangci-lint run --verbose --fix --timeout 5m ./...

  update-golden-tests:
    desc: Update {{.GENERATOR_APP}} golden test outputs.
    dir: '{{.GENERATOR_ROOT}}'
    cmds:
      - go test ./...
    env:
      GOLDIE_UPDATE: 1

  format-code:
    desc: Ensure all code for generator is formatted
    dir: '{{.GENERATOR_ROOT}}'
    cmds:
      - cmd: gofumpt -l -w .
        ignore_error: true # Just in case the code doesn't build
      - cmd: go fix ./...
        ignore_error: true # Just in case the code doesn't build

  go-mod-tidy:
    desc: Tidy the go.mod file
    dir : '{{.GENERATOR_ROOT}}'
    cmds:
      - go mod tidy

  ensure-reports-dir:
    desc: Ensure the test output directory exists
    cmds:
      - echo "Ensuring test output directory {{.TEST_OUT}} exists"
      - mkdir -p '{{.TEST_OUT}}'
    if: '[ ! -d "{{.TEST_OUT}}" ]'
