// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1api20180901

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_PrivateDnsZone_STATUS_ARM_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of PrivateDnsZone_STATUS_ARM via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForPrivateDnsZone_STATUS_ARM, PrivateDnsZone_STATUS_ARMGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForPrivateDnsZone_STATUS_ARM runs a test to see if a specific instance of PrivateDnsZone_STATUS_ARM round trips to JSON and back losslessly
func RunJSONSerializationTestForPrivateDnsZone_STATUS_ARM(subject PrivateDnsZone_STATUS_ARM) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual PrivateDnsZone_STATUS_ARM
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of PrivateDnsZone_STATUS_ARM instances for property testing - lazily instantiated by
// PrivateDnsZone_STATUS_ARMGenerator()
var privateDnsZone_STATUS_ARMGenerator gopter.Gen

// PrivateDnsZone_STATUS_ARMGenerator returns a generator of PrivateDnsZone_STATUS_ARM instances for property testing.
// We first initialize privateDnsZone_STATUS_ARMGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func PrivateDnsZone_STATUS_ARMGenerator() gopter.Gen {
	if privateDnsZone_STATUS_ARMGenerator != nil {
		return privateDnsZone_STATUS_ARMGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForPrivateDnsZone_STATUS_ARM(generators)
	privateDnsZone_STATUS_ARMGenerator = gen.Struct(reflect.TypeOf(PrivateDnsZone_STATUS_ARM{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForPrivateDnsZone_STATUS_ARM(generators)
	AddRelatedPropertyGeneratorsForPrivateDnsZone_STATUS_ARM(generators)
	privateDnsZone_STATUS_ARMGenerator = gen.Struct(reflect.TypeOf(PrivateDnsZone_STATUS_ARM{}), generators)

	return privateDnsZone_STATUS_ARMGenerator
}

// AddIndependentPropertyGeneratorsForPrivateDnsZone_STATUS_ARM is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForPrivateDnsZone_STATUS_ARM(gens map[string]gopter.Gen) {
	gens["Etag"] = gen.PtrOf(gen.AlphaString())
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Location"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Tags"] = gen.MapOf(gen.AlphaString(), gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForPrivateDnsZone_STATUS_ARM is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForPrivateDnsZone_STATUS_ARM(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(PrivateZoneProperties_STATUS_ARMGenerator())
}

func Test_PrivateZoneProperties_STATUS_ARM_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of PrivateZoneProperties_STATUS_ARM via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForPrivateZoneProperties_STATUS_ARM, PrivateZoneProperties_STATUS_ARMGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForPrivateZoneProperties_STATUS_ARM runs a test to see if a specific instance of PrivateZoneProperties_STATUS_ARM round trips to JSON and back losslessly
func RunJSONSerializationTestForPrivateZoneProperties_STATUS_ARM(subject PrivateZoneProperties_STATUS_ARM) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual PrivateZoneProperties_STATUS_ARM
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of PrivateZoneProperties_STATUS_ARM instances for property testing - lazily instantiated by
// PrivateZoneProperties_STATUS_ARMGenerator()
var privateZoneProperties_STATUS_ARMGenerator gopter.Gen

// PrivateZoneProperties_STATUS_ARMGenerator returns a generator of PrivateZoneProperties_STATUS_ARM instances for property testing.
func PrivateZoneProperties_STATUS_ARMGenerator() gopter.Gen {
	if privateZoneProperties_STATUS_ARMGenerator != nil {
		return privateZoneProperties_STATUS_ARMGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForPrivateZoneProperties_STATUS_ARM(generators)
	privateZoneProperties_STATUS_ARMGenerator = gen.Struct(reflect.TypeOf(PrivateZoneProperties_STATUS_ARM{}), generators)

	return privateZoneProperties_STATUS_ARMGenerator
}

// AddIndependentPropertyGeneratorsForPrivateZoneProperties_STATUS_ARM is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForPrivateZoneProperties_STATUS_ARM(gens map[string]gopter.Gen) {
	gens["MaxNumberOfRecordSets"] = gen.PtrOf(gen.Int())
	gens["MaxNumberOfVirtualNetworkLinks"] = gen.PtrOf(gen.Int())
	gens["MaxNumberOfVirtualNetworkLinksWithRegistration"] = gen.PtrOf(gen.Int())
	gens["NumberOfRecordSets"] = gen.PtrOf(gen.Int())
	gens["NumberOfVirtualNetworkLinks"] = gen.PtrOf(gen.Int())
	gens["NumberOfVirtualNetworkLinksWithRegistration"] = gen.PtrOf(gen.Int())
	gens["ProvisioningState"] = gen.PtrOf(gen.OneConstOf(
		PrivateZoneProperties_ProvisioningState_STATUS_Canceled,
		PrivateZoneProperties_ProvisioningState_STATUS_Creating,
		PrivateZoneProperties_ProvisioningState_STATUS_Deleting,
		PrivateZoneProperties_ProvisioningState_STATUS_Failed,
		PrivateZoneProperties_ProvisioningState_STATUS_Succeeded,
		PrivateZoneProperties_ProvisioningState_STATUS_Updating))
}
