apiVersion: sql.azure.com/v20211101
kind: ServersEncryptionProtector
metadata:
  name: aso-sample-serversencryptionprotector
  namespace: default
spec:
  owner:
    name: aso-sample-sqlserver
  serverKeyType: AzureKeyVault
  serverKeyName: aso-sample-keyvault_aso-sample-key_aso-sample-key-version
