apiVersion: redhatopenshift.azure.com/v20260901preview
kind: HcpOpenShiftCluster
metadata:
  name: aso-sample-hcp
  namespace: default
spec:
  azureName: aso-sample-hcp
  location: uksouth
  owner:
    group: resources.azure.com
    kind: ResourceGroup
    name: aso-sample-rg
  identity:
    type: UserAssigned
    userAssignedIdentities:
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-cloud-controller-manager"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-cloud-network-config"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-cluster-api-azure"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-control-plane"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-disk-csi-driver"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-file-csi-driver"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-image-registry"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-ingress"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-kms"
        - reference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-service-managed-identity"
  properties:
    platform:
      networkSecurityGroupReference:
        group: network.azure.com
        kind: NetworkSecurityGroup
        name: aso-sample-nsg
      operatorsAuthentication:
        userAssignedIdentities:
          controlPlaneOperatorsReferences:
            cloud-controller-manager:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-cloud-controller-manager"
            cloud-network-config:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-cloud-network-config"
            cluster-api-azure:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-cluster-api-azure"
            control-plane:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-control-plane"
            disk-csi-driver:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-disk-csi-driver"
            file-csi-driver:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-file-csi-driver"
            image-registry:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-image-registry"
            ingress:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-ingress"
            kms:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-cp-kms"
          dataPlaneOperatorsReferences:
            disk-csi-driver:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-dp-disk-csi-driver"
            file-csi-driver:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-dp-file-csi-driver"
            image-registry:
              armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-dp-image-registry"
          serviceManagedIdentityReference:
            armId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/aso-sample-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aso-sample-service-managed-identity"
      subnetReference:
        group: network.azure.com
        kind: VirtualNetworksSubnet
        name: "aso-sample-vnet-aso-sample-subnet"
      managedResourceGroup: "aso-sample-managed-rg"
      outboundType: LoadBalancer
    cryptoRestrictions: None
    ingress:
      type: Public
    clusterImageRegistry:
      state: Enabled
    etcd:
      dataEncryption:
        keyManagementMode: CustomerManaged
        customerManaged:
          encryptionType: KMS
          kms:
            vaultName: "aso-sample-kv"
            activeKey:
              name: "etcd-data-kms-encryption-key"
              version: "00000000000000000000000000000000"
    network:
      hostPrefix: 23
      networkType: OVNKubernetes
      machineCidr: "10.0.0.0/16"
      podCidr: "10.128.0.0/14"
      serviceCidr: "172.30.0.0/16"
    version:
      channelGroup: stable
      id: "4.19"
    api:
      visibility: Public
  tags:
    environment: production
    owner: sre-team
