apiVersion: containerregistry.azure.com/v20251101
kind: Registry
metadata:
  name: sampleregistry
spec:
  location: westus2
  owner:
    name: aso-sample-rg
  sku:
    name: Premium
  adminUserEnabled: false
  publicNetworkAccess: Enabled
  zoneRedundancy: Disabled
