apiVersion: dbformysql.azure.com/v20241230
kind: FlexibleServersAdministrator
metadata:
  name: sampleadministrator
  namespace: default
spec:
  owner:
    name: samplemysql
  administratorType: ActiveDirectory
  identityResourceReference:
    group: managedidentity.azure.com
    kind: UserAssignedIdentity
    name: adminidentity
  login: useradmin@microsoft.com
  sidFrom:
    name: admin-sid
    key: sid
  tenantIdFrom:
    name: admin-tenantid
    key: tenantid
