apiVersion: apimanagement.azure.com/v20240501
kind: GatewayCertificateAuthority
metadata:
  name: samplegatewaycertauth
  namespace: default
spec:
  azureName: samplecertificate
  isTrusted: true
  owner:
    name: samplegateway
