apiVersion: apimanagement.azure.com/v20240501
kind: Logger
metadata:
  name: samplelogger
  namespace: default
spec:
  loggerType: "azureEventHub"
  description: "A sample Event Hub logger"
  resourceReference:
    group: eventhub.azure.com
    kind: NamespacesEventhub
    name: sample-eventhub
  credentials:
    name: apim-logger-eventhub-credentials
  owner:
    name: sampleapimservice
