apiVersion: storage.azure.com/v20250601
kind: StorageAccount
metadata:
  name: samplekubestorageeg25
  namespace: default
spec:
  location: westcentralus
  kind: StorageV2
  sku:
    name: Standard_LRS
  owner:
    name: aso-sample-rg
  accessTier: Hot
